// ═══════════════════════════════════════════════════════════
// reportGenerator.js — Markdown Report Builder & PDF Export
// ═══════════════════════════════════════════════════════════

const ReportGenerator = (() => {

  const _ts = () => new Date().toLocaleDateString('en-IN', { day:'2-digit', month:'long', year:'numeric' });

  // ── SUMMARY REPORT ───────────────────────────────────────
  const buildSessionSummary = () => {
    const kg = KnowledgeGraph.all();
    const stats = KnowledgeGraph.stats();
    const insights = KnowledgeGraph.generateInsights();
    const idx = KnowledgeGraph.getFileIndex();

    const fileList = Object.entries(idx)
      .map(([name, meta]) => `| ${name} | ${meta.schema} | ${meta.rowCount} rows |`)
      .join('\n');

    // Expiry breakdown
    const expMap = {};
    kg.leases.forEach(l => {
      if (!l.endDate) return;
      try {
        const yr = new Date(l.endDate).getFullYear();
        expMap[yr] = (expMap[yr] || 0) + 1;
      } catch {}
    });
    const expRows = Object.entries(expMap).sort((a,b) => a[0]-b[0])
      .map(([yr, cnt]) => `| ${yr} | ${cnt} |`).join('\n');

    // Top sectors from tenants
    const sectorMap = {};
    kg.tenants.forEach(t => {
      if (t.sector) sectorMap[t.sector] = (sectorMap[t.sector] || 0) + 1;
    });
    const topSectors = Object.entries(sectorMap).sort((a,b) => b[1]-a[1]).slice(0, 5)
      .map(([s, c]) => `• ${s} (${c})`).join('\n');

    const avail = KnowledgeGraph.availableProperties().length;

    return `# 📊 CRE Intelligence Session Report
**Nexus Asia | CRE Intelligence Hub**
**Generated:** ${_ts()}

---

## 📂 Files Processed (${stats.files})

| File Name | Schema Detected | Records |
|-----------|-----------------|---------|
${fileList || '| — | — | — |'}

---

## 🏢 Property Inventory
- **Total Records:** ${stats.properties}
- **Available:** ${avail}
- **Occupied/Leased:** ${stats.properties - avail}

---

## 📋 Lease Database
- **Total Leases:** ${stats.leases}

### Expiry Year Breakdown
| Year | Count |
|------|-------|
${expRows || '| — | — |'}

---

## 👥 Tenants & Contacts
- **Unique Tenants:** ${stats.tenants}
- **Contacts Extracted:** ${stats.contacts}
${topSectors ? `\n### Top Sectors\n${topSectors}` : ''}

---

## 💡 Auto-Generated Insights
${insights.map(i => `- ${i}`).join('\n') || '- Upload more data for insights.'}

---

## 🗺️ Mumbai Market Benchmarks
| Micro-Market | Grade | Rent Range |
|---|---|---|
${Object.values(CONFIG.MARKETS).map(m => `| ${m.label} | ${m.grade} | ₹${m.min}–₹${m.max}/sqft |`).join('\n')}

---
*Report generated by CRE Intelligence Hub — Nexus Asia*`;
  };

  // ── EXPORT AS FILE ────────────────────────────────────────
  const downloadMarkdown = (content, filename = 'cre-session-report.md') => {
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadJSON = (content, filename = 'cre-session-data.json') => {
    const blob = new Blob([JSON.stringify(content, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportSummary = () => {
    const report = buildSessionSummary();
    downloadMarkdown(report);
    return report;
  };

  const exportData = () => {
    const data = KnowledgeGraph.all();
    downloadJSON(data);
  };

  return { buildSessionSummary, exportSummary, exportData, downloadMarkdown };
})();

window.ReportGenerator = ReportGenerator;
